

import { Brand, Category } from './types';

export const BRANDS: Brand[] = [
  {
    id: '1',
    name: 'PTT Gas Station',
    category: Category.ENERGY,
    purpose: 'Fuel Retail',
    purposeKm: 'ការលក់រាយប្រេងឥន្ធនៈ',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'pttplc.com',
    description: 'State-owned Thai oil and gas company operating widespread gas stations across Cambodia.',
    descriptionKm: 'ក្រុមហ៊ុនប្រេង និងឧស្ម័នរបស់រដ្ឋថៃ ដែលកំពុងដំណើរការស្ថានីយ៍ប្រេងឥន្ធនៈយ៉ាងទូលំទូលាយនៅទូទាំងប្រទេសកម្ពុជា។',
    imageUrl: 'https://cdn.worldvectorlogo.com/logos/ptt-station-logo.svg'
  },
  {
    id: '2',
    name: '7-Eleven',
    category: Category.RETAIL,
    purpose: 'Convenience Store',
    purposeKm: 'ហាង​ងាយស្រួល​ទិញ',
    location: 'Major Cities',
    locationKm: 'រាជធានី និងខេត្តធំៗ',
    website: '7-eleven.com',
    description: 'Operated by CP All. Aggressively expanding throughout Cambodia, replacing local convenience stores.',
    descriptionKm: 'ប្រតិបត្តិការដោយ CP All ។ កំពុងពង្រីកយ៉ាងខ្លាំងនៅទូទាំងប្រទេសកម្ពុជា ដោយជំនួសហាងលក់ទំនិញក្នុងស្រុក។',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/7-eleven_logo.svg/1024px-7-eleven_logo.svg.png'
  },
  {
    id: '3',
    name: 'Otteri Wash & Dry',
    category: Category.RETAIL,
    purpose: 'Laundry',
    purposeKm: 'បោកអ៊ុត',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'otteriwashdry.com/en',
    description: '24-hour self-service coin-operated laundry business franchise from Thailand.',
    descriptionKm: 'ហ្វ្រេនឆាយអាជីវកម្មបោកអ៊ុត 24 ម៉ោងពីប្រទេសថៃ។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRlAnjFZkfgoe_1JjVVH7TbohUWsQEgkkCXZDVuY51_cTlU4iXEUsaPxZS&s=10'
  },
  {
    id: '4',
    name: 'Big C',
    category: Category.RETAIL,
    purpose: 'Hypermarket',
    purposeKm: 'ផ្សារទំនើបខ្នាតធំ',
    location: 'Phnom Penh, Poipet',
    locationKm: 'ភ្នំពេញ, ប៉ោយប៉ែត',
    website: 'bigc.co.th',
    description: 'Major grocery retailer acquired by Berli Jucker (BJC). A primary competitor to local markets.',
    descriptionKm: 'អ្នកលក់រាយគ្រឿងទេសដ៏សំខាន់ដែលត្រូវបានទិញដោយ Berli Jucker (BJC) ។ គូប្រជែងចម្បងជាមួយផ្សារក្នុងស្រុក។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdOuDLPas076UA-PBtBkmjyJRXmmdNi3LLdPnFaMcRig&s=10'
  },
  {
    id: '5',
    name: 'Global House',
    category: Category.CONSTRUCTION,
    purpose: 'Furnitures, Appliances and Decor',
    purposeKm: 'គ្រឿងសង្ហារិម សម្ភារៈប្រើប្រាស់ និងការតុបតែង',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'globalhouse.co.th',
    description: 'Large warehouse style store for construction materials and home decoration.',
    descriptionKm: 'ហាងលក់សម្ភារៈសំណង់ និងការតុបតែងផ្ទះដ៏ធំ។',
    imageUrl: 'https://media.licdn.com/dms/image/v2/D560BAQHXyjunsRVlmw/company-logo_200_200/company-logo_200_200/0/1666760728138/siam_global_house_logo?e=2147483647&v=beta&t=AZb5euNyJMO9DvhVzf7E0VZAU7FaJdEMT6vTicmXtAk'
  },
  {
    id: '6',
    name: 'Makro',
    category: Category.RETAIL,
    purpose: 'Wholesale',
    purposeKm: 'លក់ដុំ',
    location: 'Major Cities',
    locationKm: 'រាជធានី និងខេត្តធំៗ',
    website: 'siammakro.co.th',
    description: 'Wholesale cash and carry store owned by CP Group, dominating the wholesale market.',
    descriptionKm: 'ហាងលក់ដុំដែលគ្រប់គ្រងដោយ CP Group ដែលគ្របដណ្តប់ទីផ្សារលក់ដុំ។',
    imageUrl: 'https://ayambrand.co.th/images/AYAM-Customer/logocustomer-11.png'
  },
  {
    id: '7',
    name: 'PTT Lubricants',
    category: Category.AUTOMOTIVE,
    purpose: 'Automotive',
    purposeKm: 'យានយន្ត (ប្រេងម៉ាស៊ីន)',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'pttlubricants.com',
    description: 'Automotive lubricants and fluids sold at PTT stations and retailers.',
    descriptionKm: 'ប្រេងរអិលនិងប្រេងម៉ាស៊ីនដែលលក់នៅស្ថានីយ៍ PTT និងអ្នកលក់រាយ។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMecpYpwSQyhc8LUOUfr4KYZvTcDN9Xh51YjaGFj6YoljZvz-vv4UkRkw&s=10'
  },
  {
    id: '8',
    name: 'Fit Auto',
    category: Category.AUTOMOTIVE,
    purpose: 'Auto Service',
    purposeKm: 'សេវាកម្មរថយន្ត',
    location: 'PTT Stations',
    locationKm: 'ស្ថានីយ៍ PTT',
    website: 'pttfitauto.com',
    description: 'Automotive service center chain located within PTT stations.',
    descriptionKm: 'មជ្ឈមណ្ឌលសេវាកម្មរថយន្តដែលមានទីតាំងនៅស្ថានីយ៍ PTT ។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGo_SxaGn0BrHZQ5LKMakioeHs1K__4LE4JZrY5Um-MUAn3thVWUykYvC_&s=10'
  },
  {
    id: '9',
    name: 'Hattha Bank',
    category: Category.FINANCE,
    purpose: 'Banking (Subsidiary of Krungsri)',
    purposeKm: 'ធនាគារ (បុត្រសម្ព័ន្ធរបស់ Krungsri)',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'hatthabank.com',
    description: 'Hattha Bank is a subsidiary of Krungsri Bank (Bank of Ayudhya PCL) from Thailand.',
    descriptionKm: 'ធនាគារហត្ថា គឺជាបុត្រសម្ព័ន្ធរបស់ធនាគារ Krungsri (Bank of Ayudhya PCL) មកពីប្រទេសថៃ។',
    imageUrl: 'https://i.tracxn.com/logo/company/hatthabank.com_Logo_8670de1b-1e9e-4c2a-9271-37aa084174ba.jpg'
  },
  {
    id: '10',
    name: 'CP Fresh Mart',
    category: Category.RETAIL,
    purpose: 'Mini Market',
    purposeKm: 'មីនីម៉ាត',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'cpfreshmartshop.com',
    description: 'Convenience store chain selling CP Group food products.',
    descriptionKm: 'ហាងលក់ទំនិញដែលលក់ផលិតផលអាហាររបស់ CP Group។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNAd4JBqw1_M7GZE6Oj02iVlLsZbqpBZ0yAk7Ng2BfVDATIc_Rf-Y4CMDS&s=10'
  },
  {
    id: '11',
    name: 'CP Foods',
    category: Category.FOOD_BEVERAGE,
    purpose: 'Fresh Food',
    purposeKm: 'អាហារ​ស្រស់',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'cpf.co.th',
    description: 'Charoen Pokphand Foods. Giant agro-industrial and food conglomerate.',
    descriptionKm: 'Charoen Pokphand Foods ។ ក្រុមហ៊ុនកសិឧស្សាហកម្ម និងអាហារយក្ស។',
    imageUrl: 'https://www.thefoodfellas.co.uk/wp-content/uploads/2017/01/cp-foods.jpg'
  },
  {
    id: '12',
    name: 'Fire Tiger',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Premium Drink',
    purposeKm: 'ភេសជ្ជៈពិសេស',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'firetigerfood.com',
    description: 'Thai bubble tea brand known for its tiger head branding.',
    descriptionKm: 'ម៉ាកតែគុជថៃ ដែលល្បីល្បាញដោយសាររូបក្បាលខ្លា។',
    imageUrl: 'https://firetigerfood.com/wp-content/uploads/2021/04/logo.png'
  },
  {
    id: '13',
    name: 'Five Star Chicken',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Fast Food',
    purposeKm: 'អាហារ​ទាន់​ចិត្ត',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'fivestarchicken.com',
    description: 'Fried chicken franchise by CP Group, found on many street corners.',
    descriptionKm: 'ហ្វ្រេនឆាយមាន់បំពងរបស់ CP Group ដែលមាននៅតាមដងផ្លូវជាច្រើន។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4kE2eLblbrIauTg-gybun3y91QwthR3cqwMr1oUGjR4WQ3jEpEODYZ4g&s=10'
  },
  {
    id: '14',
    name: 'Yuzu House by Honey Moni',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Coffee Shop',
    purposeKm: 'ហាង​កាហ្វេ',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: '',
    description: 'Specializes in Yuzu orange drinks and products.',
    descriptionKm: 'មានឯកទេសខាងភេសជ្ជៈ និងផលិតផលក្រូច Yuzu ។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrauN7K41jiMdokVHsLgy1J-SDhojVqSWwMHpPfuM3HQ&s=10'
  },
  {
    id: '15',
    name: 'Mama Noodles',
    category: Category.FOOD_BEVERAGE,
    purpose: 'Instant Noodles',
    purposeKm: 'មីកញ្ចប់',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'mamalover.net',
    description: 'Thai President Foods. The most popular instant noodle brand.',
    descriptionKm: 'ម៉ាកមីកញ្ចប់ដ៏ពេញនិយមបំផុតរបស់ថៃ។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSI93HRIq3-kdjB-KMK5mced4N1yTBDE51w_hlm_5ONFK8LyhNEzzXNN5jn&s=10'
  },
  {
    id: '16',
    name: 'Tao Kae Noi',
    category: Category.FOOD_BEVERAGE,
    purpose: 'Snacks',
    purposeKm: 'នំចំណី',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'taokaenoi.co.th',
    description: 'Famous seaweed snack brand.',
    descriptionKm: 'ម៉ាកសារាយសមុទ្រដ៏ល្បីល្បាញ។',
    imageUrl: 'https://th.taokaenoiglobal.com/wp-content/uploads/2022/08/tkn-global-logo.jpg'
  },
  {
    id: '17',
    name: 'Ichitan',
    category: Category.FOOD_BEVERAGE,
    purpose: 'Tea',
    purposeKm: 'តែ',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'ichitangroup.com',
    description: 'Ready-to-drink green tea manufacturer.',
    descriptionKm: 'ក្រុមហ៊ុនផលិតតែបៃតងដប។',
    imageUrl: 'https://mir-s3-cdn-cf.behance.net/projects/404/e6f31a175215721.Y3JvcCwxMzgwLDEwODAsMTAsMA.jpg'
  },
  {
    id: '18',
    name: 'Oishi',
    category: Category.FOOD_BEVERAGE,
    purpose: 'Tea',
    purposeKm: 'តែ',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'oishigroup.com',
    description: 'Japanese-style green tea and restaurants (part of Thai Bev).',
    descriptionKm: 'តែបៃតងរចនាប័ទ្មជប៉ុន និងភោជនីយដ្ឋាន (ជាផ្នែកមួយនៃ Thai Bev)។',
    imageUrl: 'https://images.hungryhub.com/uploads/restaurant/logo/5302/273052407_111149518147815_3422328617930006665_n.jpg'
  },
  {
    id: '19',
    name: 'Red Bull',
    category: Category.FOOD_BEVERAGE,
    purpose: 'Energy Drink',
    purposeKm: 'ភេសជ្ជៈ​ប៉ូវ​កម្លាំង',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'redbull.com',
    description: 'Originated in Thailand (Krating Daeng).',
    descriptionKm: 'មានប្រភពដើមនៅប្រទេសថៃ (Krating Daeng)។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQB1_Z_VKLIXyVqchBWvJzDNwqPlwE8mN9Sst8uCNg_Q&s=10'
  },
  {
    id: '20',
    name: 'Carabao',
    category: Category.FOOD_BEVERAGE,
    purpose: 'Energy Drink',
    purposeKm: 'ភេសជ្ជៈ​ប៉ូវ​កម្លាំង',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'carabao.co.th',
    description: 'Major Thai energy drink brand.',
    descriptionKm: 'ម៉ាកភេសជ្ជៈប៉ូវកម្លាំងដ៏ធំរបស់ថៃ។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPVXTzu59uKxJmsieTZhRJmCSOF1uUZzFyPQ&s'
  },
  {
    id: '21',
    name: 'Dutch Mill',
    category: Category.FOOD_BEVERAGE,
    purpose: 'Dairy',
    purposeKm: 'ផលិតផល​ទឹកដោះគោ',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'dutchmill.co.th',
    description: 'Thailand\'s largest dairy product manufacturer.',
    descriptionKm: 'ក្រុមហ៊ុនផលិតផលិតផលទឹកដោះគោធំជាងគេនៅប្រទេសថៃ។',
    imageUrl: 'https://d1ee0vqmjhj8pf.cloudfront.net/media/case_study_logo/5b76560f2bf54.jpg'
  },
  {
    id: '22',
    name: 'CP-Meiji',
    category: Category.FOOD_BEVERAGE,
    purpose: 'Dairy',
    purposeKm: 'ផលិតផល​ទឹកដោះគោ',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'cpmeiji.com',
    description: 'Pasteurized milk and yogurt.',
    descriptionKm: 'ទឹកដោះគោ និងទឹកដោះគោជូរ។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSb1-yqR0PBWFxPbom_et_RqxV4Vde6zoBefqvjSsijigvVW-7-rAGddARe&s=10'
  },
  {
    id: '23',
    name: 'Malee',
    category: Category.FOOD_BEVERAGE,
    purpose: 'Juice',
    purposeKm: 'ទឹក​ផ្លែឈើ',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'malee.co.th',
    description: 'Fruit juices and canned fruits.',
    descriptionKm: 'ទឹកផ្លែឈើ និងផ្លែឈើកំប៉ុង។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRQ3ETmx09knnbTLnhoFjT4mxvOmY_Ryqs9OIsR5PM5A_fVDzzYvCn-v8&s=10'
  },
  {
    id: '24',
    name: 'Leo Beer',
    category: Category.FOOD_BEVERAGE,
    purpose: 'Beer',
    purposeKm: 'ស្រាបៀរ',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'boonrawd.co.th',
    description: 'Produced by Boon Rawd Brewery.',
    descriptionKm: 'ផលិតដោយក្រុមហ៊ុនស្រាបៀរ Boon Rawd ។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTV7QFsVcdW7J1b-yLSZZThaFKZq8tIVBFAMcaJT8APG4aLFVULYXocX6Q_&s=10'
  },
  {
    id: '25',
    name: 'Singha',
    category: Category.FOOD_BEVERAGE,
    purpose: 'Beer',
    purposeKm: 'ស្រាបៀរ',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'singha.com',
    description: 'The original Thai beer, by Boon Rawd Brewery.',
    descriptionKm: 'ស្រាបៀរថៃដើម ផលិតដោយក្រុមហ៊ុនស្រាបៀរ Boon Rawd ។',
    imageUrl: 'https://singha.com/images/download-resources/full/download-resources-01.jpg'
  },
  {
    id: '26',
    name: 'Chang',
    category: Category.FOOD_BEVERAGE,
    purpose: 'Beer',
    purposeKm: 'ស្រាបៀរ',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'changbeer.com',
    description: 'Produced by Thai Beverage (ThaiBev).',
    descriptionKm: 'ផលិតដោយ Thai Beverage (ThaiBev)។',
    imageUrl: 'https://images.seeklogo.com/logo-png/2/2/chang-logo-png_seeklogo-29031.png'
  },
  {
    id: '27',
    name: 'Betagro',
    category: Category.FOOD_BEVERAGE,
    purpose: 'Meat',
    purposeKm: 'សាច់',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'betagro.com',
    description: 'Agro-industrial and food conglomerate.',
    descriptionKm: 'ក្រុមហ៊ុនកសិឧស្សាហកម្ម និងអាហារ។',
    imageUrl: 'https://bongsrey.sgp1.digitaloceanspaces.com/library/20240/images/thumbnail/60cdd49250ba6.png'
  },
  {
    id: '28',
    name: 'Tipco',
    category: Category.FOOD_BEVERAGE,
    purpose: 'Juice',
    purposeKm: 'ទឹក​ផ្លែឈើ',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'tipco.net',
    description: 'Fruit juice market leader in Thailand.',
    descriptionKm: 'អ្នកដឹកនាំទីផ្សារទឹកផ្លែឈើនៅប្រទេសថៃ។',
    imageUrl: 'https://awards.brandingforum.org/wp-content/uploads/2016/11/Tipco-Logo-1-1024x1024.jpg'
  },
  {
    id: '29',
    name: 'Cafe Amazon',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Coffee',
    purposeKm: 'កាហ្វេ',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'cafe-amazon.com',
    description: 'The largest coffee chain in Thailand, a subsidiary of PTT Group.',
    descriptionKm: 'ហាងកាហ្វេធំជាងគេនៅប្រទេសថៃ ជាបុត្រសម្ព័ន្ធរបស់ PTT Group។',
    imageUrl: 'https://images.seeklogo.com/logo-png/37/1/cafe-amazon-logo-png_seeklogo-373926.png'
  },
  {
    id: '30',
    name: 'TOUS les JOURS',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Baked Goods',
    purposeKm: 'នំនិងនំបុ័ង',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: '',
    description: 'Operated by EFG (Express Food Group), often associated with Thai management in region.',
    descriptionKm: 'ប្រតិបត្តិការដោយ EFG (Express Food Group) ដែលជាញឹកញាប់ត្រូវបានផ្សារភ្ជាប់ជាមួយនឹងការគ្រប់គ្រងរបស់ថៃនៅក្នុងតំបន់។',
    imageUrl: 'https://edengarden.com.kh/wp-content/uploads/2025/05/Tous-Les-Jours.jpg'
  },
  {
    id: '31',
    name: 'Inthanin',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Coffee',
    purposeKm: 'កាហ្វេ',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'inthanincoffee.com',
    description: 'Chain coffee shop owned by Bangchak Corporation.',
    descriptionKm: 'ហាងកាហ្វេគ្រប់គ្រងដោយ Bangchak Corporation។',
    imageUrl: 'https://franchisepremium.com/wp-content/uploads/2025/02/LOGO_Inthanin.png'
  },
  {
    id: '32',
    name: 'Black Canyon',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Restaurant',
    purposeKm: 'ភោជនីយដ្ឋាន',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'blackcanyonthai.com',
    description: 'Long-running Thai restaurant and coffee shop chain.',
    descriptionKm: 'ភោជនីយដ្ឋាន និងហាងកាហ្វេថៃដែលដំណើរការយូរមកហើយ។',
    imageUrl: 'https://contents.bu.ac.th/contents/images/mous/059b5101-0039-44ad-9195-45a8f3858a6a.jpg'
  },
  {
    id: '33',
    name: 'Chao Doi',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Coffee',
    purposeKm: 'កាហ្វេ',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'chaodoi.co.th',
    description: 'Thai coffee brand.',
    descriptionKm: 'ម៉ាកកាហ្វេថៃ។',
    imageUrl: 'https://ice-maker.happycool-th.com/wp-content/uploads/2024/04/co2hc-logo.jpg'
  },
  {
    id: '34',
    name: 'ChaTraMue',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Thai Tea',
    purposeKm: 'តែ​ថៃ',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'cha-thai.com',
    description: 'Original Thai Tea brand since 1945.',
    descriptionKm: 'ម៉ាកតែថៃដើមតាំងពីឆ្នាំ 1945 ។',
    imageUrl: 'https://cms-tpq.theparq.com/wp-content/uploads/2020/07/ChaTraMue_Logo-01_800x800.png'
  },
  {
    id: '35',
    name: 'S&P',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Restaurant',
    purposeKm: 'ភោជនីយដ្ឋាន',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'snpfood.com',
    description: 'Restaurant and bakery chain.',
    descriptionKm: 'ខ្សែសង្វាក់ភោជនីយដ្ឋាន និងហាងនំប៉័ង។',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/S%26P_Logo.svg/1200px-S%26P_Logo.svg.png'
  },
  {
    id: '36',
    name: 'After You',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Dessert',
    purposeKm: 'បង្អែម',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'afteryoudessertcafe.com',
    description: 'Popular dessert cafe famous for Shibuya Toast.',
    descriptionKm: 'ហាងកាហ្វេបង្អែមដ៏ពេញនិយម ល្បីល្បាញដោយសារ Shibuya Toast។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJw5agHik55Eq6huDnaNTckryiAJbrloj5gsFXQcPq6qrjWyRxAnPv5sI&s=10'
  },
  {
    id: '37',
    name: 'MK Suki',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Hotpot',
    purposeKm: 'ស៊ុគី',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'mkrestaurant.com',
    description: 'Famous Thai hotpot restaurant chain.',
    descriptionKm: 'ហាងស៊ុគីដ៏ល្បីល្បាញរបស់ថៃ។',
    imageUrl: 'https://www.iamchinatownbkk.com/wp-content/uploads/2024/12/357088756_664392092399721_3373257924149755544_n.jpg'
  },
  {
    id: '38',
    name: 'True Coffee',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Coffee',
    purposeKm: 'កាហ្វេ',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'truecoffee.co.th',
    description: 'Coffee chain owned by True Corporation (CP Group).',
    descriptionKm: 'ហាងកាហ្វេដែលគ្រប់គ្រងដោយ True Corporation (CP Group)។',
    imageUrl: 'https://www.truedigitalpark.com/public/uploads/shop/47f470a0406d29ad950bd018d397a61b.png'
  },
  {
    id: '39',
    name: 'Bar-B-Q Plaza',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'BBQ',
    purposeKm: 'សាច់អាំង',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'barbqplaza.com',
    description: 'Self-cooking BBQ restaurant from Thailand.',
    descriptionKm: 'ភោជនីយដ្ឋានសាច់អាំងដោយខ្លួនឯងមកពីប្រទេសថៃ។',
    imageUrl: 'https://the-mines.com.my/wp-content/uploads/sites/7/2024/01/Bar-B-Q-Plaza-Logo.jpg'
  },
  {
    id: '40',
    name: 'Santa Fé',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Steak',
    purposeKm: 'ស្ទេក',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: '',
    description: 'Steak and western food restaurant chain.',
    descriptionKm: 'ហាងលក់ស្ទេក និងអាហារលោកខាងលិច។',
    imageUrl: 'https://santafesteak.com/santafesteak/img/logo.png'
  },
  {
    id: '41',
    name: 'Yuzu Suki',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Modern Japanese Dining',
    purposeKm: 'អាហារជប៉ុនទំនើប',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'yuzugroup2018.com',
    description: 'Japanese dining concept under Yuzu Group.',
    descriptionKm: 'គោលគំនិតនៃការទទួលទានអាហារជប៉ុនក្រោម Yuzu Group។',
    imageUrl: 'https://media-cdn.tripadvisor.com/media/photo-m/1280/27/13/94/6f/yuzu-suki-siam-center.jpg'
  },
  {
    id: '42',
    name: 'The Pizza Company',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Pizza',
    purposeKm: 'ភីហ្សា',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: '1112.com',
    description: 'Thai-owned pizza franchise, operated by EFG.',
    descriptionKm: 'ហ្វ្រេនឆាយភីហ្សាដែលគ្រប់គ្រងដោយថៃ ប្រតិបត្តិការដោយ EFG ។',
    imageUrl: 'https://foodbuzz.site/api/v1/files/6c6e2c5f-592a-4811-8bcc-a7409e75f876'
  },
  {
    id: '43',
    name: 'Swensen’s',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Ice Cream',
    purposeKm: 'ការ៉េម',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'swensens1112.com',
    description: 'Operated by Minor Food Group (Thai) in the region.',
    descriptionKm: 'ប្រតិបត្តិការដោយ Minor Food Group (Thai) ក្នុងតំបន់។',
    imageUrl: 'https://images.seeklogo.com/logo-png/20/2/swensens-logo-png_seeklogo-202603.png'
  },
  {
    id: '44',
    name: 'The Coffee Club',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Cafe',
    purposeKm: 'ហាង​កាហ្វេ',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'thecoffeeclub.co.th',
    description: 'Australian brand owned by Minor International (Thai).',
    descriptionKm: 'ម៉ាកយីហោអូស្ត្រាលីដែលគ្រប់គ្រងដោយ Minor International (ថៃ)។',
    imageUrl: 'https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://thecoffeeclub.co.th&size=128'
  },
  {
    id: '45',
    name: 'Dairy Queen',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Ice Cream',
    purposeKm: 'ការ៉េម',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'dairyqueen.co.th',
    description: 'Operated regionally by Minor Food Group.',
    descriptionKm: 'ប្រតិបត្តិការក្នុងតំបន់ដោយ Minor Food Group ។',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Dairy_Queen_logo.svg'
  },
  {
    id: '46',
    name: 'Krispy Kreme',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Donuts',
    purposeKm: 'នំដូណាត់',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'krispykreme.co.th',
    description: 'Regional franchise management linked to Thai entities.',
    descriptionKm: 'ការគ្រប់គ្រងហ្វ្រេនឆាយក្នុងតំបន់ដែលភ្ជាប់ទៅនឹងក្រុមហ៊ុនថៃ។',
    imageUrl: 'https://images.seeklogo.com/logo-png/49/1/krispy-kreme-logo-png_seeklogo-490553.png'
  },
  {
    id: '47',
    name: 'Boost Juice',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Juice',
    purposeKm: 'ទឹក​ផ្លែឈើ',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'boostjuicebars.in.th',
    description: 'Operated by EFG/Minor Food Group.',
    descriptionKm: 'ប្រតិបត្តិការដោយ EFG/Minor Food Group ។',
    imageUrl: 'https://the-parq.sgp1.digitaloceanspaces.com/2023/08/22105749/Untitled-design.png'
  },
  {
    id: '48',
    name: 'Major Cineplex',
    category: Category.ENTERTAINMENT,
    purpose: 'Cinema',
    purposeKm: 'រោងកុន',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'majorcineplex.com',
    description: 'Largest cinema operator in Thailand.',
    descriptionKm: 'ប្រតិបត្តិកររោងកុនធំបំផុតនៅប្រទេសថៃ។',
    imageUrl: 'https://yt3.googleusercontent.com/lXixvraOQr0ko4l-p4XXepnMLalPsEc_mI_1fDBQl9tRU-k-vIEe106KMsIOOjlbmtzy3o0hMQ=s900-c-k-c0x00ffffff-no-rj'
  },
  {
    id: '49',
    name: 'SCB Bank',
    category: Category.FINANCE,
    purpose: 'Banking (known as CCB Bank)',
    purposeKm: 'ធនាគារ',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'scb.co.th',
    description: 'Siam Commercial Bank, operating as Cambodian Commercial Bank (CCB).',
    descriptionKm: 'ធនាគារ Siam Commercial Bank ដែលប្រតិបត្តិការជាធនាគារពាណិជ្ជកម្ពុជា (CCB)។',
    imageUrl: 'https://eu-images.contentstack.com/v3/assets/blt7dacf616844cf077/bltaa38a578f87e2e75/679955e3786c5ab6989b2a58/Siam-Commercial-Bank-2.png?width=1280&auto=webp&quality=80&format=jpg&disable=upscale'
  },
  {
    id: '50',
    name: 'True Money',
    category: Category.FINANCE,
    purpose: 'Payment',
    purposeKm: 'ការទូទាត់ប្រាក់',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'truemoney.com',
    description: 'Fintech company providing payment services, part of Ascend Group (CP Group).',
    descriptionKm: 'ក្រុមហ៊ុន Fintech ផ្តល់សេវាកម្មទូទាត់ប្រាក់ ដែលជាផ្នែកមួយនៃ Ascend Group (CP Group)។',
    imageUrl: 'https://images.seeklogo.com/logo-png/49/2/truemoney-logo-png_seeklogo-491917.png'
  },
  {
    id: '51',
    name: 'SCG',
    category: Category.CONSTRUCTION,
    purpose: 'Cement',
    purposeKm: 'ស៊ីម៉ងត៍',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'scg.com',
    description: 'Siam Cement Group. The largest cement and building material conglomerate in the region.',
    descriptionKm: 'Siam Cement Group ។ ក្រុមហ៊ុនបេតុង និងសម្ភារៈសំណង់ដ៏ធំបំផុតនៅក្នុងតំបន់។',
    imageUrl: 'https://blue.star-board.com/wp-content/uploads/2022/05/Starboard-Blue-Team-Partner-SCG-Logo-Cover.jpg'
  },
  {
    id: '52',
    name: 'TOA Paint',
    category: Category.CONSTRUCTION,
    purpose: 'Paint',
    purposeKm: 'ថ្នាំលាប',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'toagroup.com',
    description: 'Leading paint manufacturer from Thailand.',
    descriptionKm: 'ក្រុមហ៊ុនផលិតថ្នាំលាបឈានមុខគេមកពីប្រទេសថៃ។',
    imageUrl: 'https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://toagroup.com&size=128'
  },
  {
    id: '53',
    name: 'Cotto',
    category: Category.CONSTRUCTION,
    purpose: 'Tiles',
    purposeKm: 'ការ៉ូ',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'cotto.com',
    description: 'Ceramic tiles and sanitary ware, part of SCG.',
    descriptionKm: 'ក្បឿងសេរ៉ាមិច និងបរិក្ខារបន្ទប់ទឹក ដែលជាផ្នែកមួយនៃ SCG ។',
    imageUrl: 'https://images.seeklogo.com/logo-png/20/2/cotto-logo-png_seeklogo-202235.png'
  },
  {
    id: '54',
    name: 'Kubota',
    category: Category.AGRICULTURE,
    purpose: 'Machinery',
    purposeKm: 'គ្រឿងចក្រ',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'siamkubota.co.th',
    description: 'Siam Kubota. Agricultural machinery.',
    descriptionKm: 'Siam Kubota ។ គ្រឿងចក្រកសិកម្ម។',
    imageUrl: 'https://images.seeklogo.com/logo-png/27/1/kubota-logo-png_seeklogo-278931.png'
  },
  {
    id: '55',
    name: 'JWD Logistics',
    category: Category.LOGISTICS,
    purpose: 'Logistics',
    purposeKm: 'ដឹកជញ្ជូន',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'jwd-group.com',
    description: 'Logistics and supply chain solutions.',
    descriptionKm: 'ដំណោះស្រាយភស្តុភារ និងសង្វាក់ផ្គត់ផ្គង់។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQyU-YiKTWHEZ_WQ6-KyuG5MfHXRRa4zobWepcVQy0mCd6l1xoq-JLex88&s=10'
  },
  {
    id: '56',
    name: 'CC Double O',
    category: Category.FASHION,
    purpose: 'Clothing',
    purposeKm: 'សម្លៀកបំពាក់',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'ccdoubleo.com',
    description: 'American luxury style fashion brand by Jaspal Group.',
    descriptionKm: 'ម៉ាកសម្លៀកបំពាក់ប្រណិតរបស់ Jaspal Group ។',
    imageUrl: 'https://ampp.aeonmallcambodia.com/wp-content/uploads/sites/2/2023/12/b8718758-8f69-4d66-a7f1-e0fe27e5a159.jpg'
  },
  {
    id: '57',
    name: 'Jaspal',
    category: Category.FASHION,
    purpose: 'Clothing',
    purposeKm: 'សម្លៀកបំពាក់',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'jaspal.com',
    description: 'Major Thai fashion retailer.',
    descriptionKm: 'អ្នកលក់រាយម៉ូដសំលៀកបំពាក់ថៃដ៏ធំ។',
    imageUrl: 'https://pbs.twimg.com/profile_images/1225589111186018305/6XuuCAsD_400x400.jpg'
  },
  {
    id: '58',
    name: 'LYN',
    category: Category.FASHION,
    purpose: 'Bags',
    purposeKm: 'កាបូប',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'lynaccs.com',
    description: 'Fashion accessories and bags by Jaspal Group.',
    descriptionKm: 'គ្រឿងសម្ភារៈម៉ូដ និងកាបូបដោយ Jaspal Group ។',
    imageUrl: 'https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://lynaccs.com&size=128'
  },
  {
    id: '59',
    name: 'Pomelo',
    category: Category.FASHION,
    purpose: 'Clothing',
    purposeKm: 'សម្លៀកបំពាក់',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'pomelofashion.com',
    description: 'Bangkok-based fashion e-commerce platform and stores.',
    descriptionKm: 'វេទិកាពាណិជ្ជកម្មអេឡិចត្រូនិក និងហាងដែលមានមូលដ្ឋាននៅទីក្រុងបាងកក។',
    imageUrl: 'https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://pomelofashion.com&size=128'
  },
  {
    id: '60',
    name: 'DAPPER',
    category: Category.FASHION,
    purpose: 'Men',
    purposeKm: 'បុរស',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'dapper.com',
    description: 'Menswear and leather accessories.',
    descriptionKm: 'សម្លៀកបំពាក់បុរស និងគ្រឿងស្បែក។',
    imageUrl: 'https://dapper.com/wp-content/uploads/2019/12/DPlogolaz.png'
  },
  {
    id: '61',
    name: 'Mistine',
    category: Category.COSMETICS,
    purpose: 'Cosmetics',
    purposeKm: 'គ្រឿងសម្អាង',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'mistine.co.th',
    description: 'Direct selling cosmetic brand.',
    descriptionKm: 'ម៉ាកគ្រឿងសម្អាងលក់ផ្ទាល់។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcKkUerCL-I0AYqLuN2tiZo1qVOGTyo8zqWU2AkZZg_w6cmL-MiH03ZUE&s=10'
  },
  {
    id: '62',
    name: 'Oriental Princess',
    category: Category.COSMETICS,
    purpose: 'Skincare',
    purposeKm: 'ថែរក្សាស្បែក',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'orientalprincess.com',
    description: 'Beauty and lifestyle brand.',
    descriptionKm: 'ម៉ាកសម្រស់ និងរបៀបរស់នៅ។',
    imageUrl: 'https://assets.tryandreview.com/uploads/images/brands/efca03b3eccc4c8bce306bd169d913e51a8f7574.png'
  },
  {
    id: '63',
    name: 'Srichand',
    category: Category.COSMETICS,
    purpose: 'Skincare',
    purposeKm: 'ថែរក្សាស្បែក',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'srichand.com',
    description: 'Famous for its translucent powder.',
    descriptionKm: 'ល្បីល្បាញដោយសារម្សៅផាត់មុខ។',
    imageUrl: 'https://th-test-11.slatic.net/shop/980a478eb92c275ba9e0dfe6e723b1c9.png'
  },
  {
    id: '64',
    name: '4U2',
    category: Category.COSMETICS,
    purpose: 'Makeup',
    purposeKm: 'ការតុបតែងមុខ',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: '4u2thailand.com',
    description: 'Youth-oriented makeup brand.',
    descriptionKm: 'ម៉ាកតុបតែងមុខសម្រាប់យុវវ័យ។',
    imageUrl: 'https://www.watsonsinternational.com/only-at-watsons/assets/images/4u2_cosmetics/logo.jpg'
  },
  {
    id: '65',
    name: 'Cathy Doll',
    category: Category.COSMETICS,
    purpose: 'Skincare',
    purposeKm: 'ថែរក្សាស្បែក',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'cathydolls.com',
    description: 'Korean-inspired Thai cosmetic brand by Karmarts.',
    descriptionKm: 'ម៉ាកគ្រឿងសម្អាងថៃដែលបំផុសគំនិតដោយកូរ៉េ ដោយ Karmarts ។',
    imageUrl: 'https://cathydoll.me/cdn/shop/files/New_CD_LOGO_2018.png?v=1669460778&width=2188'
  },
  {
    id: '66',
    name: 'Baby Bright',
    category: Category.COSMETICS,
    purpose: 'Skincare',
    purposeKm: 'ថែរក្សាស្បែក',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'karmarts.co.th',
    description: 'Nature-inspired cosmetics by Karmarts.',
    descriptionKm: 'គ្រឿងសម្អាងបំផុសគំនិតដោយធម្មជាតិ ដោយ Karmarts ។',
    imageUrl: 'https://mms.img.susercontent.com/th-11134216-81zth-mg9hsxmv1xqka8'
  },
  {
    id: '67',
    name: 'Snail White',
    category: Category.COSMETICS,
    purpose: 'Skincare',
    purposeKm: 'ថែរក្សាស្បែក',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'namulife.com',
    description: 'Famous for snail secretion filtrate products.',
    descriptionKm: 'ល្បីល្បាញដោយសារផលិតផលចំរាញ់ចេញពីទឹករីរ។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtVFpqpXRCyj2ZEpUG9T4F9eqyMEpUuIocnx7VC9sPXi3c4hACpbitGiU&s=10'
  },
  {
    id: '68',
    name: 'Cute Press',
    category: Category.COSMETICS,
    purpose: 'Skincare',
    purposeKm: 'ថែរក្សាស្បែក',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'cutepress.com',
    description: 'Affordable quality cosmetics.',
    descriptionKm: 'គ្រឿងសម្អាងដែលមានគុណភាពសមរម្យ។',
    imageUrl: 'https://inwfile.com/s-cv/j0u1ec.jpg'
  },
  {
    id: '69',
    name: 'Jelly Bunny',
    category: Category.FASHION,
    purpose: 'Bag and Shoes',
    purposeKm: 'កាបូបនិងស្បែកជើង',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'jellybunnymy.com',
    description: 'Playful shoe and bag brand by Jaspal Group.',
    descriptionKm: 'ម៉ាកស្បែកជើង និងកាបូបរបស់ Jaspal Group។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsDcWr_w32EM1GZCY_4j8YaMVareEreEys-Q&s'
  },
  {
    id: '70',
    name: 'Dr.Tiger Laundry',
    category: Category.RETAIL,
    purpose: 'Laundry',
    purposeKm: 'បោកអ៊ុត',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'drtigerld.com',
    description: 'Laundry franchise.',
    descriptionKm: 'ហ្វ្រេនឆាយបោកអ៊ុត។',
    imageUrl: 'https://thai-franchise.com/wp-content/uploads/2024/08/Dr.Tiger-Laundry-LOGO.png'
  },
  {
    id: '71',
    name: 'KASIKORNBANK',
    category: Category.FINANCE,
    purpose: 'Banking',
    purposeKm: 'ធនាគារ',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'kasikornbank.com',
    description: 'Also known as KBank.',
    descriptionKm: 'ត្រូវបានគេស្គាល់ផងដែរថាជា KBank ។',
    imageUrl: 'https://www.kasikornbank.com/SiteCollectionDocuments/about/img/logo/logo.png'
  },
  {
    id: '72',
    name: 'Denta Joy',
    category: Category.HEALTHCARE,
    purpose: 'Dental Clinic',
    purposeKm: 'គ្លីនិកធ្មេញ',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'dentajoy.com/en/home/',
    description: 'Specialized dental clinic and a leading innovator in the field of orthodontics.',
    descriptionKm: 'គ្លីនិកធ្មេញឯកទេស និងជាអ្នកបង្កើតថ្មីឈានមុខគេក្នុងវិស័យអញ្ចាញធ្មេញ។',
    imageUrl: 'https://d21wppy61jc2vt.cloudfront.net/9ecf7ddbe96ca3c6fdc7bd0583874aed199393a57b7702864b35b26ed35b6709-thumb'
  },
  {
    id: '73',
    name: 'Yerpall',
    category: Category.COSMETICS,
    purpose: 'Skincare',
    purposeKm: 'ថែរក្សាស្បែក',
    location: 'Online shops and Retailers',
    locationKm: 'ហាងអនឡាញ និងអ្នកលក់រាយ',
    website: 'yerpallthailand.com',
    description: 'Thai skincare brand popular online.',
    descriptionKm: 'ម៉ាកផលិតផលថែរក្សាស្បែករបស់ថៃ ដែលពេញនិយមតាមអ៊ីនធឺណិត។',
    imageUrl: 'https://down-th.img.susercontent.com/file/th-11134233-7rasg-m3kyg8sawpmj1d'
  },
  {
    id: '74',
    name: 'Soursdey Finance',
    category: Category.FINANCE,
    purpose: 'Leasing Company',
    purposeKm: 'ក្រុមហ៊ុនជួល',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'tk.co.th/suosdey',
    description: 'Leasing and finance subsidiary.',
    descriptionKm: 'បុត្រសម្ព័ន្ធជួល និងហិរញ្ញវត្ថុ។',
    imageUrl: 'https://hrincjobs-pro.s3.amazonaws.com/media/public/filer_public/0b/a8/0ba87f1b-4b32-4488-8ffb-d85c3ce67f64/suosdey-01.jpg'
  },
  {
    id: '75',
    name: 'Lyyon',
    category: Category.FOOD_BEVERAGE,
    purpose: 'Water',
    purposeKm: 'ទឹក',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: '',
    description: 'Drinking water brand.',
    descriptionKm: 'ម៉ាកទឹកផឹក។',
    imageUrl: 'https://media.makrocambodiaclick.com/PRODUCT_1591070483697.jpeg'
  },
  {
    id: '76',
    name: 'Doi Chaang',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Coffee Shop',
    purposeKm: 'ហាង​កាហ្វេ',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'doichaangcoffee.co.th',
    description: 'Premium coffee brand.',
    descriptionKm: 'ម៉ាកកាហ្វេលំដាប់ខ្ពស់។',
    imageUrl: 'https://doichaangcoffee.co.th/wp-content/uploads/2025/05/logo-doichaang.png'
  },
  {
    id: '77',
    name: 'Kamu Kamu',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Milktea',
    purposeKm: 'តែ​ទឹកដោះគោ',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'kamutea.com',
    description: 'Japanese style tea and milk tea.',
    descriptionKm: 'តែរចនាប័ទ្មជប៉ុន និងតែទឹកដោះគោ។',
    imageUrl: 'https://kh.kamutea.com/wp-content/uploads/2023/07/Real-Fruit-Green-tea.png'
  },
  {
    id: '78',
    name: 'U-90 Paint',
    category: Category.CONSTRUCTION,
    purpose: 'Construction Material, Paint',
    purposeKm: 'សម្ភារៈសំណង់ ថ្នាំលាប',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'uraipaints.com',
    description: 'Paint and construction chemicals.',
    descriptionKm: 'ថ្នាំលាប និងគីមីសំណង់។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0_WdTAVP7U8VUXWt5gBZLkj3ftgLBFxt_FjrNwGukAnELsKP1u3PyqDdt&s=10'
  },
  {
    id: '79',
    name: 'Lub D',
    category: Category.HOSPITALITY,
    purpose: 'Accommodation',
    purposeKm: 'កន្លែងស្នាក់នៅ',
    location: 'Siem Reap',
    locationKm: 'សៀមរាប',
    website: 'lubd.com',
    description: 'Social hotel and hostel chain.',
    descriptionKm: 'សណ្ឋាគារ និងផ្ទះសំណាក់។',
    imageUrl: 'https://e7.pngegg.com/pngimages/27/799/png-clipart-lub-d-phuket-patong-hotel-backpacker-hostel-lub-d-cambodia-siem-reap-accommodation-lodge-blue-text.png'
  },
  {
    id: '80',
    name: 'Sofitel Phnom Penh Phokeethra',
    category: Category.HOSPITALITY,
    purpose: 'Hotel',
    purposeKm: 'សណ្ឋាគារ',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: '',
    description: 'Partly owned by Thai entity Thai Nakorn Patana Co. Ltd.',
    descriptionKm: 'ជាកម្មសិទ្ធិដោយផ្នែករបស់ក្រុមហ៊ុនថៃ Thai Nakorn Patana Co. Ltd.',
    imageUrl: 'https://my.sofitel-phnompenh-phokeethra.com/wp-content/uploads/2021/08/logo-icon.png'
  },
  {
    id: '81',
    name: 'Kozue Omakase',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Japanese Restaurant',
    purposeKm: 'ភោជនីយដ្ឋានជប៉ុន',
    location: 'Beung Keng Kang',
    locationKm: 'បឹងកេងកង',
    website: 'kozueomakase.com',
    description: 'Japanese restaurant owned by Thai entities.',
    descriptionKm: 'ភោជនីយដ្ឋានជប៉ុនគ្រប់គ្រងដោយថៃ។',
    imageUrl: 'https://img.salehere.co.th/p/1200x0/2023/05/23/avr6yk8lefk0.jpg'
  },
  {
    id: '82',
    name: 'Springmate',
    category: Category.HOUSEHOLD_OFFICE,
    purpose: 'Bed Stuff & Mattresses',
    purposeKm: 'ពូក និងខ្នើយ',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'springmate.com',
    description: 'Bedding and mattress brand.',
    descriptionKm: 'ម៉ាកពូក និងខ្នើយ។',
    imageUrl: 'https://image.makewebeasy.net/makeweb/m_1920x0/UoFkSNozd/Springmate/Springmate_logo.jpg?v=202012190947'
  },
  {
    id: '83',
    name: 'Hungry App',
    category: Category.LOGISTICS,
    purpose: 'Delivery App',
    purposeKm: 'កម្មវិធីដឹកជញ្ជូន',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'Hungryapp.asia',
    description: 'Food and Beverage Delivery App operated by EFG.',
    descriptionKm: 'កម្មវិធីដឹកជញ្ជូនអាហារ និងភេសជ្ជៈ ប្រតិបត្តិការដោយ EFG។',
    imageUrl: 'https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://Hungryapp.asia&size=128'
  },
  {
    id: '84',
    name: 'Tumkratoei',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Thai Cuisine',
    purposeKm: 'ម្ហូបថៃ',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: '',
    description: 'Authentic Thai restaurant (តាំក្រាធេីយ).',
    descriptionKm: 'ភោជនីយដ្ឋានថៃ (តាំក្រាធេីយ)។',
    imageUrl: 'https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://N/A&size=128'
  },
  {
    id: '85',
    name: 'Royal Angkor International Hospital',
    category: Category.HEALTHCARE,
    purpose: 'Hospital',
    purposeKm: 'មន្ទីរពេទ្យ',
    location: 'Siem Reap',
    locationKm: 'សៀមរាប',
    website: 'bangkokhospital.com',
    description: 'Part of Bangkok Dusit Medical Services (BDMS).',
    descriptionKm: 'ផ្នែកនៃ Bangkok Dusit Medical Services (BDMS)។',
    imageUrl: 'https://static.wixstatic.com/media/dab058_527de92e9f264f43820634f84ea0ca27~mv2.png/v1/fill/w_280,h_197,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/Logo_Bangkok-Hospital-2019-489.png'
  },
  {
    id: '86',
    name: 'Royal Phnom Penh Hospital',
    category: Category.HEALTHCARE,
    purpose: 'Hospital',
    purposeKm: 'មន្ទីរពេទ្យ',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'bangkokhospital.com',
    description: 'Part of Bangkok Dusit Medical Services (BDMS).',
    descriptionKm: 'ផ្នែកនៃ Bangkok Dusit Medical Services (BDMS)។',
    imageUrl: 'https://static.wixstatic.com/media/dab058_527de92e9f264f43820634f84ea0ca27~mv2.png/v1/fill/w_280,h_197,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/Logo_Bangkok-Hospital-2019-489.png'
  },
  {
    id: '87',
    name: 'Park Hyatt Hotel Siem Reap',
    category: Category.HOSPITALITY,
    purpose: 'Hotel',
    purposeKm: 'សណ្ឋាគារ',
    location: 'Siem Reap',
    locationKm: 'សៀមរាប',
    website: 'hyatt.com',
    description: 'Hotel owned by a Thai entity, Hotel De La Paix, Co. Ltd.',
    descriptionKm: 'សណ្ឋាគារដែលគ្រប់គ្រងដោយក្រុមហ៊ុនថៃ Hotel De La Paix, Co. Ltd.',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNA1oDQtaB1jMAgEwyb5KOCFo18xQUveIx_VZ5ADAPswAMpsOjFCkXwjw&s=10'
  },
  {
    id: '88',
    name: 'Star Coffee',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Coffee Shop',
    purposeKm: 'ហាង​កាហ្វេ',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: '',
    description: 'Coffee Shop owned by Thai conglomerate.',
    descriptionKm: 'ហាងកាហ្វេគ្រប់គ្រងដោយក្រុមហ៊ុនថៃ។',
    imageUrl: 'https://images.deliveryhero.io/image/fd-kh/Products/1871744.jpg?width=%25s'
  },
  {
    id: '89',
    name: 'YOSOYA THAI FOOD',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Thai Cuisine',
    purposeKm: 'ម្ហូបថៃ',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'yosaya-thai-food.menu-world.com',
    description: 'Thai Dishes and Cuisines.',
    descriptionKm: 'ម្ហូបថៃ។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCa5NXSygbrbjsL15DKATyqHKw4p1aRr3QgtlcPVufMEUxcpsjPORXHGKn&s=10'
  },
  {
    id: '90',
    name: 'Coffee I Need You',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Cafe',
    purposeKm: 'ហាង​កាហ្វេ',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: '',
    description: 'Eatery, coffee and bakery supply.',
    descriptionKm: 'អាហារដ្ឋាន កាហ្វេ និងហាងនំប៉័ង។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEUcFT6FOjJ96zPRFJ_r9WW-PhHlSCDm0KLoSFPMvL-wM721Kj_Uc15Os&s=10'
  },
  {
    id: '91',
    name: 'Mama Thai Restaurant',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Thai Cuisine',
    purposeKm: 'ម្ហូបថៃ',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: '',
    description: 'Thai Dishes and Cuisines.',
    descriptionKm: 'ម្ហូបថៃ។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWEztd77PX_FqETfkGQ8KimLxDItTn-I5sMG-XXLHJtyySdH8F6BKWl2ts&s=10'
  },
  {
    id: '92',
    name: 'Dentisté',
    category: Category.COSMETICS,
    purpose: 'Toothpaste',
    purposeKm: 'ថ្នាំដុសធ្មេញ',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'dentiste-oralcare.com',
    description: 'Premium toothpaste brand.',
    descriptionKm: 'ម៉ាកថ្នាំដុសធ្មេញគុណភាពខ្ពស់។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTE7C5H4ABl529DOjMhYfkhuFU1pp_SWQhP0cq8IFtOpzwXQ6pTtbnJQnQ&s=10'
  },
  {
    id: '93',
    name: 'Palmolive',
    category: Category.COSMETICS,
    purpose: 'Shampoo',
    purposeKm: 'សាប៊ូកក់សក់',
    location: 'Retailers',
    locationKm: 'អ្នកលក់រាយ',
    website: 'colgatepalmolive.co.th',
    description: 'Only Thai imports.',
    descriptionKm: 'ការនាំចូលពីប្រទេសថៃប៉ុណ្ណោះ។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLcMFPOK2xNTIcp9QY4YAM_yVNwW_oy-OfL-W4ANLjomaTvlPRic8PJAo&s=10'
  },
  {
    id: '94',
    name: '361 THREE SIX ONE',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Cafe Shop',
    purposeKm: 'ហាង​កាហ្វេ',
    location: 'Siem Reap, Battambang',
    locationKm: 'សៀមរាប, បាត់ដំបង',
    website: 'facebook.com/share/1A4ioNR7Dj',
    description: 'Cafe Shop.',
    descriptionKm: 'ហាង​កាហ្វេ។',
    imageUrl: 'https://sgp1.digitaloceanspaces.com/facetaste/places/633f858ae72d038032364133/0eIu40-jdbVy3rsMxq_cL.jpg?s=1920x1920&bh=UgQ%2CL1xu-%3Bxuj%5Bayofj%5B%7EqayIUj%5B%3Fbj%5BRjfQ'
  },
  {
    id: '95',
    name: 'Baoji',
    category: Category.FASHION,
    purpose: 'Sport Shoes',
    purposeKm: 'ស្បែកជើងកីឡា',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'baoji.co.th',
    description: 'Sport shoes brand.',
    descriptionKm: 'ម៉ាកស្បែកជើងកីឡា។',
    imageUrl: 'https://allonline.7eleven.co.th/media/i/logo_baoji_14-166937-0.jpg'
  },
  {
    id: '96',
    name: 'Bububee',
    category: Category.FASHION,
    purpose: 'Bag',
    purposeKm: 'កាបូប',
    location: 'Aeon Sensok',
    locationKm: 'ផ្សារទំនើប អ៊ីអន',
    website: 'aeonmalllogiplus.com.kh/brand/bu-bu-bee',
    description: 'Bag store.',
    descriptionKm: 'ហាងលក់កាបូប។',
    imageUrl: 'https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://aeonmalllogiplus.com.kh/brand/bu-bu-bee&size=128'
  },
  {
    id: '97',
    name: 'M-150',
    category: Category.FOOD_BEVERAGE,
    purpose: 'Energy Drink',
    purposeKm: 'ភេសជ្ជៈ​ប៉ូវ​កម្លាំង',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'osotspa.com',
    description: 'Thailand\'s top-selling energy beverage.',
    descriptionKm: 'ភេសជ្ជៈប៉ូវកម្លាំងលក់ដាច់បំផុតរបស់ប្រទេសថៃ។',
    imageUrl: 'https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://www.osotspa.com/en/our-brands/6/m-150&size=128'
  },
  {
    id: '98',
    name: 'Phai Saan',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Thai Cuisine',
    purposeKm: 'ម្ហូបថៃ',
    location: 'Koh Norea',
    locationKm: 'កោះនរា',
    website: '',
    description: 'Thai Cuisine.',
    descriptionKm: 'ម្ហូបថៃ។',
    imageUrl: 'https://scontent.fpnh5-3.fna.fbcdn.net/v/t39.30808-6/466857840_2330743143956796_6820777091965073472_n.jpg?_nc_cat=106&ccb=1-7&_nc_sid=6ee11a&_nc_ohc=5xaqPTTT5csQ7kNvwE--q5S&_nc_oc=AdnMkSKXcigvcfzyKnMCn8_faZldxBnevi2Mqfqhz-vWkSlw-41nzcdrVaA8YW8Frxk&_nc_zt=23&_nc_ht=scontent.fpnh5-3.fna&_nc_gid=ptReBef6nD53L70JNTUNTQ&oh=00_AfkCbun0pxof_7o9kjC9_TivlCzyZI8Bj7NDTCOs42XnNw&oe=694137FC'
  },
  {
    id: '99',
    name: 'Kai Zaab',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Thai Cuisine',
    purposeKm: 'ម្ហូបថៃ',
    location: 'BKK',
    locationKm: 'បឹងកេងកង',
    website: '',
    description: 'Thai Cuisine.',
    descriptionKm: 'ម្ហូបថៃ។',
    imageUrl: 'https://scontent.fpnh5-3.fna.fbcdn.net/v/t39.30808-6/326923817_574849124141102_6431109079156547723_n.jpg?_nc_cat=104&ccb=1-7&_nc_sid=6ee11a&_nc_ohc=rUbrTeM_4W0Q7kNvwErwNC1&_nc_oc=AdmCizegivUfAhCEVJnU7T5cBZ4dXdEWYYssC7K0I0FEcM9vIMQbj6yYPBsxT_4eS7Q&_nc_zt=23&_nc_ht=scontent.fpnh5-3.fna&_nc_gid=EfU6vh0pNmsYgIWggXe94w&oh=00_Afk058Lngd4Dl3J14bfhzsMnNcUbK4_zCG4ZVR67VHoGAg&oe=69414D78'
  },
  {
    id: '100',
    name: 'FCC Angkor',
    category: Category.HOSPITALITY,
    purpose: 'Hotel',
    purposeKm: 'សណ្ឋាគារ',
    location: 'Siem Reap',
    locationKm: 'សៀមរាប',
    website: 'avanihotels.com',
    description: 'Accommodation linked to Avani Hotels of Minor Hotels.',
    descriptionKm: 'កន្លែងស្នាក់នៅភ្ជាប់ទៅ Avani Hotels នៃ Minor Hotels ។',
    imageUrl: 'https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://www.avanihotels.com/en&size=128'
  },
  {
    id: '101',
    name: 'Dim Sum Emperors',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Dim Sum',
    purposeKm: 'ឌីមសាំ',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'expressfoodgroup.com',
    description: 'Operated by EFG.',
    descriptionKm: 'ប្រតិបត្តិការដោយ EFG ។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStdCf1Ia6HnqYzE5Q_uq1NoDCZM0bSUr5Ywg&s'
  },
  {
    id: '102',
    name: 'Zebra',
    category: Category.HOUSEHOLD_OFFICE,
    purpose: 'Household products',
    purposeKm: 'ផលិតផលប្រើប្រាស់ក្នុងផ្ទះ',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: '',
    description: 'Stainless steel kitchenware.',
    descriptionKm: 'សម្ភារៈផ្ទះបាយដែកអ៊ីណុក។',
    imageUrl: 'https://www.sibucookwarecentre.my/image/sibucoo/image/data/IMG_1967.JPG'
  },
  {
    id: '103',
    name: 'Mama Thai',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Thai Restaurant',
    purposeKm: 'ភោជនីយដ្ឋានថៃ',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'maps.app.goo.gl/qibcmPgdSkWC4vAB7',
    description: 'Famous Thai Restaurant in BKK.',
    descriptionKm: 'ភោជនីយដ្ឋានថៃដ៏ល្បីនៅបឹងកេងកង។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpuSCn_1C9JUfB7tDu7CdBToDHbpZBYvhFJg&s'
  },
  {
    id: '104',
    name: 'BluO',
    category: Category.ENTERTAINMENT,
    purpose: 'Bowling & Karaoke',
    purposeKm: 'ប៊ូលីង និងខារ៉ាអូខេ',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'bluofriends.com',
    description: 'Entertainment complex.',
    descriptionKm: 'មជ្ឈមណ្ឌលកម្សាន្ត។',
    imageUrl: 'https://www.bluofriends.com/wp-content/uploads/2019/07/BluO-Logo.png'
  },
  {
    id: '105',
    name: 'Double A',
    category: Category.HOUSEHOLD_OFFICE,
    purpose: 'Paper',
    purposeKm: 'ក្រដាស',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: 'doubleapaper.com',
    description: 'Premium copy paper.',
    descriptionKm: 'ក្រដាសថតចម្លងគុណភាពខ្ពស់។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8jy8OBb91NdGbbk3k5ucEQlDv6uBziQ6OsdhfIxIzDltmHO6hTX2sKO8&s=10'
  },
  {
    id: '106',
    name: 'Hatari',
    category: Category.ELECTRONICS,
    purpose: 'Fan',
    purposeKm: 'កង្ហារ',
    location: 'Retailers',
    locationKm: 'អ្នកលក់រាយ',
    website: 'hatari.co.th',
    description: 'Electric fans.',
    descriptionKm: 'កង្ហារអគ្គិសនី។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDY14-s5Y7Ojfebg7JBV93RA6VaKEMzEQdutqw0KQ4ODpdeowDV0407Z0&s=10'
  },
  {
    id: '107',
    name: 'Fuji Restaurant',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Restaurant',
    purposeKm: 'ភោជនីយដ្ឋាន',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'fuji.co.th',
    description: 'Japanese restaurant.',
    descriptionKm: 'ភោជនីយដ្ឋានជប៉ុន។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQX4PDWxB3qZ42a_sr5NGxfQ70sEuLgE0YlwQ&s'
  },
  {
    id: '108',
    name: 'Colgate',
    category: Category.COSMETICS,
    purpose: 'Toothpaste',
    purposeKm: 'ថ្នាំដុសធ្មេញ',
    location: 'Retailers',
    locationKm: 'អ្នកលក់រាយ',
    website: 'colgateprofessional.co.th',
    description: 'Only Thai Imports.',
    descriptionKm: 'ការនាំចូលពីប្រទេសថៃប៉ុណ្ណោះ។',
    imageUrl: 'https://www.colgatepalmolive.co.th/content/dam/cp-sites/corporate/corporate-2021/our/brands/colgate.png'
  },
  {
    id: '109',
    name: 'Smooth E',
    category: Category.COSMETICS,
    purpose: 'Skincare',
    purposeKm: 'ថែរក្សាស្បែក',
    location: 'Nationwide',
    locationKm: 'ទូទាំងប្រទេស',
    website: '',
    description: 'Skincare products.',
    descriptionKm: 'ផលិតផលថែរក្សាស្បែក។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTn8U128EnvEwJZyFk3yAsjg49mkhC7kO3bCQ&s'
  },
  {
    id: '110',
    name: 'Maya Thai Taste',
    category: Category.CAFES_RESTAURANTS,
    purpose: 'Thai Cuisine',
    purposeKm: 'ម្ហូបថៃ',
    location: 'Sen Sok',
    locationKm: 'សែនសុខ',
    website: 'facebook.com/share/17SbD8RqVj',
    description: 'Thai Cuisine.',
    descriptionKm: 'ម្ហូបថៃ។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4Wbo9Kh0JHUvWZGhS3CiAgQwgRh7DFHK4Yg&s'
  },
  {
    id: '111',
    name: 'Krung Thai Bank',
    category: Category.FINANCE,
    purpose: 'Banking',
    purposeKm: 'ធនាគារ',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'krungthai.com',
    description: 'Phnom Penh Branch.',
    descriptionKm: 'សាខាភ្នំពេញ។',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/th/2/29/%E0%B8%98%E0%B8%99%E0%B8%B2%E0%B8%84%E0%B8%B2%E0%B8%A3%E0%B8%81%E0%B8%A3%E0%B8%B8%E0%B8%87%E0%B9%84%E0%B8%97%E0%B8%A2.png'
  },
  {
    id: '112',
    name: 'Bangkok Bank',
    category: Category.FINANCE,
    purpose: 'Banking',
    purposeKm: 'ធនាគារ',
    location: 'Phnom Penh',
    locationKm: 'ភ្នំពេញ',
    website: 'bangkokbank.com',
    description: 'Cambodia Business Banking.',
    descriptionKm: 'សេវាកម្មធនាគារអាជីវកម្មកម្ពុជា។',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSZ_rgtcfzxzgvVWf6B5OPr9nI3U97Aafwog&s'
  }
];